[package]
name = "AMZL-Staffing"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1.1"
once_cell = "1.20.2"
config = "0.15.6"
toml = "0.8.19"
