name: Release Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: x86_64-pc-windows-gnu, x86_64-unknown-linux-gnu

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64 wine

      - name: Build Windows
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Build Linux
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Archive Windows
        uses: actions/upload-artifact@v4
        with:
          name: release-windows
          path: target/x86_64-pc-windows-gnu/release/*.exe

      - name: Archive Linux
        uses: actions/upload-artifact@v4
        with:
          name: release-linux
          path: target/x86_64-unknown-linux-gnu/release/
