name: Release Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

        include:
          - os: windows-latest

            artifact: "*.exe"

          - os: ubuntu-latest

            artifact: "*-unknown-linux-gnu"

          - os: macos-latest

            artifact: "*-apple-darwin"

    steps:
      - name: Checkout code

        uses: actions/checkout@v4

      - name: Setup Rust

        uses: dtolnay/rust-toolchain@master

        with:
          toolchain: stable

          targets: x86_64-pc-windows-msvc, x86_64-unknown-linux-gnu, x86_64-apple-darwin

      - name: Build

        run: cargo build --release

      - name: Archive Release

        uses: actions/upload-artifact@v4

        with:
          name: release-${{ matrix.os }}

          path: target/release/${{ matrix.artifact }}
