name: Release Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable-x86_64-pc-windows-msvc
          override: true

      - name: Build
        run: cargo build --release

      - name: Archive Release
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: target/release/*.exe
